#!/bin/bash
#
# collectd    Startup script for the Collectd statistics gathering daemon
# chkconfig: - 99 01
# description: Collectd is a statistics gathering daemon used to collect \
#   system information ie. cpu, memory, disk, network
# processname: collectd
# config: /opt/collectd-5.4.0/etc/collectd.conf
# pidfile: /var/run/collectd.pid

# Source function library.
. /etc/init.d/functions

RETVAL=0
ARGS=""
prog="collectd"
service="collectd"
COLLECTD_ROOT="/opt/collectd-5.4.2"
CONFIG=${COLLECTD_ROOT}/etc/collectd.conf
COLLECTD=${COLLECTD_ROOT}/sbin/collectd
COLLECTDPIDDIR="${COLLECTD_ROOT}/var/run"
COLLECTDPID="$COLLECTDPIDDIR/collectd.pid"

MAXWAIT=30

if [ -r /etc/sysconfig/$service ]; then
	. /etc/sysconfig/$service
fi

if [[ ! -d $COLLECTDPIDDIR ]]; then
	mkdir -p $COLLECTDPIDDIR
	[ -n "${RUNAS}" ] && chown "${RUNAS}:" "$COLLECTDPIDDIR"
fi

check_config() {
        if test ! -r "$CONFIG"; then
                return 2
        fi
        if ! $COLLECTD -t -C "$CONFIG"; then
                return 1
        fi
        return 0
}

start () {
	echo -n $"Starting collectd: "
	check_config
	rc="$?"
	if test "$rc" -ne 0; then
		RETVAL=6
		echo $"not starting due to configuration error"
		failure $"not starting $service due to configuration error"
	else
		daemon --user "${RUNAS:-root}" $COLLECTD -C "$CONFIG" $ARGS
		RETVAL=$?
		echo
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$service
	fi
}

stop () {
	echo -n $"Stopping collectd: "
	killproc -p $COLLECTDPID -d $MAXWAIT $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$service
}

restart () {
	check_config
	rc="$?"
	if test "$rc" -ne 0; then
		RETVAL=6
		echo $"not restarting due to configuration error"
		failure $"not restarting $service due to configuration error"
	else
		stop
		start
	fi
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p $COLLECTDPID $prog
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -f /var/lock/subsys/$service ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
	exit 1
esac

exit $?

# vim:syntax=sh
